# Generated by Django 4.1.4 on 2023-02-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemcode', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Item Code')),
                ('itemname', models.TextField(max_length=100, verbose_name='Item Name')),
                ('slug', models.TextField(max_length=100, null=True)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('image', models.ImageField(null='NOT NULL', upload_to='item_img/')),
                ('itemstatus', models.CharField(default='AVAILABLE', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Name')),
                ('course', models.TextField(max_length=30, verbose_name='Course')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('password', models.TextField(default='', max_length=25, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(verbose_name='Start Date')),
                ('enddate', models.DateField(verbose_name='End Date')),
                ('status', models.BooleanField(default=True)),
                ('itemcode', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='Reservation.item')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.student')),
            ],
        ),
    ]
