# Generated by Django 4.1.4 on 2023-02-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0005_rename_password_student_password1_student_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password2',
        ),
    ]
