# Generated by Django 4.1.4 on 2023-02-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0006_rename_password1_student_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.TextField(blank=True, max_length=30, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.TextField(blank=True, default='NULL', max_length=25, verbose_name='Password'),
        ),
    ]
