# Generated by Django 4.1.4 on 2023-02-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0007_alter_student_course_alter_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
