# Generated by Django 4.1.4 on 2023-02-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0010_remove_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startdate',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
