# Generated by Django 4.1.4 on 2023-02-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0011_alter_booking_enddate_alter_booking_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='itemcode',
            field=models.ForeignKey(blank=True, max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reservation.item'),
        ),
    ]
