# Generated by Django 4.1.4 on 2023-02-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0013_item_image2_item_image3_item_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(null=True, upload_to='item2_img/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(null=True, upload_to='item3_img/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image4',
            field=models.ImageField(null=True, upload_to='item4_img/'),
        ),
    ]
