# Generated by Django 4.1.4 on 2023-02-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0015_alter_item_image2_alter_item_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingstatus',
            field=models.BooleanField(default=True),
        ),
    ]
