# Generated by Django 4.1.4 on 2023-02-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0016_booking_bookingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='itemcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reservation.item'),
        ),
    ]
