# Generated by Django 4.1.4 on 2023-02-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0019_item_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='condition',
        ),
    ]
